import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  title = 'gened1004-cf-project';
  section_title = '';
  section_text = '';

  sections = [
    "Growing up with a close family member that has cystic fibrosis (CF), I have become interested in the technologies that are being developed to help people with his condition. Recently, a breakthrough medication called Trikafta was approved by the FDA, which helps to correctly fold the protein that is falsely generated by deleterious mutations in the Delta F508 gene (where most CF cases arise from). That being said, I have created a project that details (1) the history of our understanding of CF, (2) the biological basis of the disease, (3) past medications and treatments, (4) the new Trikafta drug, and (5) the future outlook on research into cures. Through these sections, the reader can see many triumphs of modern science, but they will also be able to recognize the failures which have darkened this history.",
    "e",
    "l",
    "l",
    "o",
    "w",
    "o",
    "r",
    "l",
    "d"
  ]
}
